services:
    # Album
    animadou_app_album_admin:
        class: Animadou\Bundle\AppBundle\Admin\AlbumAdmin
        arguments: [ @animadou_app.album_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }
        calls:
            - [addChild, [@animadou_app_photo_admin]]

    animadou_app.album_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Animadou\Bundle\AppBundle\Entity\Album ]
        parent: msi_cmf.manager

    # Photo
    animadou_app_photo_admin:
        class: Animadou\Bundle\AppBundle\Admin\PhotoAdmin
        arguments: [ @animadou_app.photo_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }
        calls:
            - [setParent, [@animadou_app_album_admin]]

    animadou_app.photo_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Animadou\Bundle\AppBundle\Entity\Photo ]
        parent: msi_cmf.manager
