animadoo_app:
    resource: "@AnimadooAppBundle/Resources/config/routing.xml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

msi_admin:
    resource: "@MsiAdminBundle/Resources/config/routing/routing.xml"

msi_admin_loader:
    resource: .
    type: msi_admin

msi_menu:
    resource: "@MsiMenuBundle/Resources/config/routing/menu.yml"

msi_page:
    resource: "@MsiPageBundle/Resources/config/routing/page.xml"
