parameters:
#    ani_user.example.class: Ani\UserBundle\Example

services:
#    ani_user.example:
#        class: %ani_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
