parameters:
#    ani_core.example.class: Ani\CoreBundle\Example

services:
    # PageSlide
    ani_core_page_slide_admin:
        class: Ani\CoreBundle\Admin\PageSlideAdmin
        arguments: [ @ani_core.page_slide_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }
        calls:
            - [setParent, [@msi_cmf_page_admin]]

    ani_core.page_slide_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Ani\CoreBundle\Entity\PageSlide ]
        parent: msi_cmf.manager
